apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-kubernetes-resource-monitor
  namespace: kube-system
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cronjob-kubernetes-resource-monitor
          containers:
          - name: cronjob-kubernetes-resource-monitor
            image: cotv/kubernetes-resource-monitor:1.0.2
            resources:
              requests:
                cpu: 100m
                memory: 128M
            envFrom:
            - secretRef:
                name: secret-kubernetes-resource-monitor
            env:
            - name: NODE_FILTER
              value: "k8s-00-dev-wor"
            - name: CLUSTER
              value: "k8s-00-dev"
            - name: ELASTIC_URL
              value: "https://elasticsearch.cotv.dk:9200"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
