---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cronjob-kubernetes-resource-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-sa-cronjob-kubernetes-resource-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-cronjob-kubernetes-resource-monitor
subjects:
- kind: ServiceAccount
  name: sa-cronjob-kubernetes-resource-monitor
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-cronjob-kubernetes-resource-monitor
  namespace: default
rules:
- apiGroups: ["extensions", "apps", "autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - deployments
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]